version: '3.4'

services:
  server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - migrations
      - db
  db:
    container_name: db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "STRONG!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14331:1433"
    depends_on:
      - migrations
  migrations:
    container_name: migration
    build:
      context: .
      dockerfile: Migrations.Dockerfile
